* Paperless office interface

  Reads the texts of images and makes them browsable and searchable via HTTP.

** Requirements

   On an Ubuntu system run the following to install prerequisites for the OCR
   and processing:

   #+begin_src shell
   sudo apt-get install sqlite3 tesseract-ocr-osd tesseract-ocr-fin tesseract-ocr imagemagick unpaper
   #+end_src

   Also Golang is required. Tested with go 1.8.

** Building the application

   Clone this repository and run the following command:

   #+begin_src shell
   go build
   #+end_src

** Usage

   Start the web server with the following:

   #+begin_src shell
   ./paperless
   #+end_src

   This starts a web-server to the port 8078. See the '--help' argument for
   command line options

   File uploading happens with a browser. There is the '+' button which opens
   a panel where one can drag-and-drop images to OCR.

** Running this inside Docker

   If you have Docker properly set up, you can run this inside docker with the
   following:

   #+begin_src shell
   cd docker
   ./run.sh
   #+end_src

   This should start an Ubuntu 16.04 Docker instance where the program is
   running.

** License

   MIT license
